const express = require('express');
const mongoose = require('mongoose');
const cors = require('cors');
const helmet = require('helmet');
const morgan = require('morgan');
const rateLimit = require('express-rate-limit');
const path = require('path');

require('dotenv').config();

// =====================================================
// 🔍 VALIDATE ENVIRONMENT VARIABLES
// =====================================================

const requiredEnvVars = [
  'MONGODB_URI',
  'JWT_SECRET',
  'OPENAI_API_KEY',
];

const missingEnvVars = requiredEnvVars.filter(
  (key) => !process.env[key]
);

if (missingEnvVars.length > 0) {
  console.error(
    '❌ MISSING ENVIRONMENT VARIABLES:',
    missingEnvVars.join(', ')
  );

  console.error(
    '⚠️ Please set all required environment variables before starting the server'
  );

  process.exit(1);
}

console.log(
  '✅ All required environment variables are set'
);

// =====================================================
// 📦 IMPORT ROUTES
// =====================================================

const authRoutes = require('./routes/auth');
const resumeRoutes = require('./routes/resume');
const interviewRoutes = require('./routes/interview');
const feedbackRoutes = require('./routes/feedback');

// =====================================================
// 🚀 CREATE EXPRESS APP
// =====================================================

const app = express();

// =====================================================
// 🔐 SECURITY MIDDLEWARE
// =====================================================

app.use(
  helmet({
    crossOriginResourcePolicy: {
      policy: 'cross-origin',
    },
  })
);

app.use(morgan('dev'));

// =====================================================
// 🚦 RATE LIMITING
// =====================================================

const limiter = rateLimit({
  windowMs: 15 * 60 * 1000,
  max: 100,

  standardHeaders: true,
  legacyHeaders: false,

  message: {
    error:
      'Too many requests, please try again later.',
  },
});

app.use('/api/', limiter);

// =====================================================
// 🌐 CORS CONFIGURATION
// =====================================================
//
// IMPORTANT:
// Your frontend can be accessed from:
// 1. Production Vercel domain
// 2. Vercel preview deployments
// 3. localhost during development
//
// Preview URLs generated by Vercel can change,
// therefore we use a dynamic origin check.
//
// =====================================================

const allowedOrigins = [
  'http://localhost:3000',
  'http://localhost:5000',

  // Production frontend
  'https://interview-ai-one-sepia.vercel.app',

  // Backend itself (not normally required for browser calls,
  // but kept for compatibility)
  'https://interviewai-1-xfn8.onrender.com',
];

// =====================================================
// CHECK WHETHER ORIGIN IS ALLOWED
// =====================================================

const isAllowedOrigin = (origin) => {
  // Requests without an Origin header can be allowed.
  //
  // This includes:
  // - server-to-server requests
  // - Postman
  // - curl
  // - some browser requests
  //
  if (!origin) {
    return true;
  }

  // Exact allowed origins
  if (allowedOrigins.includes(origin)) {
    return true;
  }

  // ===================================================
  // VERCEL PREVIEW DEPLOYMENTS
  // ===================================================
  //
  // Example:
  //
  // https://interview-cs67bbi04-aloktiwari1095-5319s-projects.vercel.app
  //
  // Vercel generates different preview URLs, so don't
  // hard-code only one preview URL.
  //
  // ===================================================

  try {
    const url = new URL(origin);

    if (
      url.protocol === 'https:' &&
      url.hostname.endsWith('.vercel.app')
    ) {
      return true;
    }
  } catch (err) {
    console.warn(
      '⚠️ Invalid origin received:',
      origin
    );

    return false;
  }

  return false;
};

// =====================================================
// CORS OPTIONS
// =====================================================

const corsOptions = {
  origin: (origin, callback) => {
    if (isAllowedOrigin(origin)) {
      callback(null, true);
    } else {
      console.warn(
        '🚫 CORS blocked origin:',
        origin
      );

      callback(
        new Error(
          `CORS blocked origin: ${origin}`
        )
      );
    }
  },

  methods: [
    'GET',
    'POST',
    'PUT',
    'DELETE',
    'PATCH',
    'OPTIONS',
  ],

  allowedHeaders: [
    'Content-Type',
    'Authorization',
  ],

  credentials: true,

  optionsSuccessStatus: 204,
};

// =====================================================
// APPLY CORS
// =====================================================

app.use(cors(corsOptions));

// =====================================================
// PREFLIGHT REQUESTS
// =====================================================

app.options('*', cors(corsOptions));

// =====================================================
// 📦 BODY PARSERS
// =====================================================

app.use(
  express.json({
    limit: '10mb',
  })
);

app.use(
  express.urlencoded({
    extended: true,
    limit: '10mb',
  })
);

// =====================================================
// 📁 STATIC FILES
// =====================================================

app.use(
  '/uploads',
  express.static(
    path.join(__dirname, 'uploads')
  )
);

// =====================================================
// 🚀 API ROUTES
// =====================================================

app.use(
  '/api/auth',
  authRoutes
);

app.use(
  '/api/resume',
  resumeRoutes
);

app.use(
  '/api/interview',
  interviewRoutes
);

app.use(
  '/api/feedback',
  feedbackRoutes
);

// =====================================================
// ❤️ HEALTH CHECK
// =====================================================

app.get(
  '/api/health',
  (req, res) => {
    res.status(200).json({
      status: 'OK',
      timestamp:
        new Date().toISOString(),
      version: '1.0.0',
    });
  }
);

// =====================================================
// 🏠 ROOT ROUTE
// =====================================================

app.get(
  '/',
  (req, res) => {
    res.status(200).json({
      success: true,
      message:
        'InterviewAI backend is running',
      timestamp:
        new Date().toISOString(),
    });
  }
);

// =====================================================
// ❌ 404 HANDLER
// =====================================================

app.use(
  (req, res) => {
    res.status(404).json({
      error: 'Route not found',
      path: req.originalUrl,
    });
  }
);

// =====================================================
// ❌ GLOBAL ERROR HANDLER
// =====================================================

app.use(
  (err, req, res, next) => {
    console.error(
      '❌ SERVER ERROR:',
      err
    );

    // CORS error
    if (
      err?.message &&
      err.message.startsWith(
        'CORS blocked origin'
      )
    ) {
      return res.status(403).json({
        error: 'CORS policy blocked this request',
        message: err.message,
      });
    }

    const statusCode =
      err?.statusCode ||
      err?.status ||
      500;

    const message =
      err?.message ||
      'Internal Server Error';

    res.status(statusCode).json({
      error: message,
    });
  }
);

// =====================================================
// 🗄️ MONGODB + SERVER START
// =====================================================

const PORT =
  process.env.PORT || 5000;

const startServer = async () => {
  try {
    console.log(
      '🔄 Connecting to MongoDB...'
    );

    await mongoose.connect(
      process.env.MONGODB_URI
    );

    console.log(
      '✅ MongoDB connected successfully'
    );

    app.listen(
      PORT,
      () => {
        console.log(
          `🚀 Server running on port ${PORT}`
        );

        console.log(
          `❤️ Health check: /api/health`
        );
      }
    );
  } catch (err) {
    console.error(
      '❌ MongoDB connection error:',
      err?.message || err
    );

    process.exit(1);
  }
};

// =====================================================
// START APPLICATION
// =====================================================

startServer();

// =====================================================
// EXPORT APP
// =====================================================

module.exports = app;
